# This is a config for E2B sandbox template.
# You can use template ID (zfm8l5uhlzlzi2rk1qvl) or template name (nextjs-venu-web-ai-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("nextjs-venu-web-ai-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("nextjs-venu-web-ai-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('nextjs-venu-web-ai-test')

team_id = "49566dea-1a7f-40e1-8660-72205b0ec5c6"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "nextjs-venu-web-ai-test"
template_id = "zfm8l5uhlzlzi2rk1qvl"
